---
name: Jekyll

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v4

      - name: Install Jekyll
        run: sudo gem install jekyll bundler

      - name: Automation
        run: cd BuildingAWesbite && jekyll build && cp -r _site ../docs/
